# Generated by Django 4.2 on 2025-04-08 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=24)),
                ('crm', models.CharField(max_length=34)),
                ('email', models.EmailField(max_length=34)),
                ('especialidade', models.CharField(choices=[('Pediatra', 'Pediatra'), ('Clinico Geral', 'Clinico Geral'), ('Ortopedista', 'Ortopedista'), ('Cirurgião', 'Cirurgião'), ('CAR', 'Cardiologistas')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.CharField(max_length=30)),
                ('data', models.DateTimeField()),
                ('status', models.CharField(choices=[('Agendaado', 'Agendado'), ('Realizado', 'Realizado'), ('Cancelado', 'cancelado')], max_length=10)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.medico')),
            ],
        ),
    ]
